version: "3"
services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/volumes/walltaker_database2:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=heffe6661
      - POSTGRES_USER=postgres

  web:
    build: .
    volumes:
            - ./:/ror
    ports:
            - "3000:3000"
    depends_on:
            - database
    environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=heffe6661

